-- ResumeCraft commerce schema
-- PostgreSQL 13+; IDs are generated by the application so no extensions are required.

create table if not exists products (
  id text primary key,
  name text not null,
  description text not null default '',
  amount integer not null check (amount >= 0),
  currency char(3) not null default 'INR',
  active boolean not null default true,
  download_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists customers (
  id text primary key,
  name text,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id text primary key,
  order_number text not null unique,
  customer_id text references customers(id),
  product_id text not null references products(id),
  status text not null check (status in ('CREATED','PENDING','PAID','FAILED','REFUNDED','CANCELLED')),
  amount integer not null check (amount >= 0),
  currency char(3) not null,
  razorpay_order_id text unique,
  razorpay_payment_id text unique,
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists webhook_events (
  event_id text primary key,
  event_type text not null,
  payload jsonb not null,
  processed_at timestamptz not null default now()
);

create table if not exists downloads (
  id text primary key,
  order_id text not null unique references orders(id) on delete cascade,
  token_hash text not null unique,
  download_count integer not null default 0,
  max_downloads integer not null default 5,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  last_downloaded_at timestamptz
);

create table if not exists coupons (
  id text primary key,
  code text not null unique,
  discount_percent integer check (discount_percent between 1 and 100),
  discount_amount integer check (discount_amount >= 0),
  active boolean not null default true,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  check ((discount_percent is not null) <> (discount_amount is not null))
);

create table if not exists audit_logs (
  id bigserial primary key,
  actor text not null,
  action text not null,
  resource_type text,
  resource_id text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_created_at on orders(created_at desc);
create index if not exists idx_webhook_events_type on webhook_events(event_type);
create index if not exists idx_downloads_order_id on downloads(order_id);

insert into products (id, name, description, amount, currency, active, download_path)
values (
  'modern-resume-pack',
  'Modern Resume Pack',
  'Clean, editable and ATS-friendly resume resources.',
  9900,
  'INR',
  true,
  'product-pack.html'
)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  amount = excluded.amount,
  currency = excluded.currency,
  active = excluded.active,
  download_path = excluded.download_path,
  updated_at = now();
